name: Build plugin

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching any tag format, i.e. 1.0, 20.15.10

env:
  PLUGIN_NAME: logseq-copy-code-plugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x' # You might need to adjust this value to your own version
      - name: Build
        id: build
        run: |
          npm i && npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp README.md package.json icon.png ${{ env.PLUGIN_NAME }}
          mv dist ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls
          echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        id: upload_artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.PLUGIN_NAME }}
          path:
            ./${{ env.PLUGIN_NAME }}.zip
